[package]
edition = "2021"
name = "bzip2"
version = "0.6.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["bzip", "encoding"]
repository = "https://github.com/trifectatechfoundation/bzip2-rs"
homepage = "https://github.com/trifectatechfoundation/bzip2-rs"
documentation = "https://docs.rs/bzip2"
description = """
Bindings to libbzip2 for bzip2 compression and decompression exposed as
Reader/Writer streams.
"""
categories = ["compression", "api-bindings"]
rust-version = "1.82.0" # MSRV
publish = true

[workspace]

[dependencies]
bzip2-sys = { version = "0.1.13", path = "bzip2-sys", optional = true }

[dependencies.libbz2-rs-sys]
version = "0.2.1"
# Don't enable the stdio feature for better portability.
default-features = false
features = ["rust-allocator"]
optional = true

[dev-dependencies]
rand = "0.9"
partial-io = { version = "0.5.4", features = ["quickcheck1"] }
quickcheck = "1.0"

[features]
default = ["dep:libbz2-rs-sys"] 
# Use the C bzip2 implementation. This will try to find the bzip2 dynamic library on your system, or build it from source. 
bzip2-sys = ["dep:bzip2-sys"]
# Always build `libbz2` from C source, and statically link it.
# This flag is only meaningful when `bzip2-sys` is used,
static = ["bzip2-sys?/static"]
